# Generated by Django 5.0.7 on 2024-08-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_image1',
            field=models.ImageField(blank=True, max_length=191, null=True, upload_to='productlist/'),
        ),
        migrations.AddField(
            model_name='product',
            name='list_image2',
            field=models.ImageField(blank=True, max_length=191, null=True, upload_to='productlist/'),
        ),
    ]
