# Generated by Django 5.0.7 on 2024-09-21 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_remove_cart_product_cart_product_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.product'),
        ),
    ]
