# Generated by Django 5.0.7 on 2024-10-06 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_rename_product_variation_cart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=191)),
                ('phone', models.CharField(max_length=20)),
                ('flat_building_no', models.CharField(max_length=191)),
                ('city', models.CharField(max_length=191)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=191)),
                ('country', models.CharField(max_length=191)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
