# Generated by Django 5.0.7 on 2024-10-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0012_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
