# Generated by Django 5.0.7 on 2024-10-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0016_cart_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
